### ISSUE TITLE
come configurare

### ISSUE THREAD

**Issue by tatoviola** [lucasimons/midea-clivet-aquaswan-modbus#3]
ciao, complimenti per il progetto.
io non sono pratico quindi ti chiedi come posso fare per configurare, ho unno swan-2 con modulo wifi.
oltre a configurare il tuo codice su home assistant cosa devo fare? Ci ho provato ma non va. grazie

**Comment by lucasimons** [comment]
Ciao, allora ci sono due modi per leggere i dati uno tramite un convertitore rs485 wifi, l'altro modo con un convertitore rs45 to ttl e esphome... Te quale vorresti usare? Con esphome puoi anche imparare i parametri

**Comment by tatoviola** [comment]
innanzitutto grazie per la risposta. allora per esphome ho già tutto ma non sono bravo con il codice. quindi dimmi quale interfaccia hai usato tu in modo da sfruttare il tuo stesso codice.

**Comment by lucasimons** [comment]
Allora se sei pratico di esphome devi semplicemente fare copia incolla dei sensori... Hai già il convertitore rs485 ttl? Hai già collegato i cavi all'interno? Sul manuale c'è il controllo tramite un dispositivo proprietario elfocontrol ma i collegamenti sono quelli

**Comment by tatoviola** [comment]
si ho già tutto, però ancora non faccio i collegamenti. già ho visto dove collegare provo con esp home nel caso non dovessi riuscirci mi puoi dire tu che convertitore wifi hai usato? grazie

**Comment by lucasimons** [comment]
Comunque sia che con esphome e con il convertitore WiFi utilizzano il collegamento coi fili sulla scheda per cui il cavo dei passarlo in entrambi i casi

**Comment by tatoviola** [comment]
sisi quello mi è chiaro. è solo per una questione di codice. in modo da sfruttare tutto il tuo codice se con esphome ho problemi.

**Comment by lucasimons** [comment]
con questo codice funziona 

```

uart:
  id: mod_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
  stop_bits: 1

modbus:
  flow_control_pin: 5
  id: clivet_modbus

modbus_controller:
  - id: clivet
    ## the Modbus device addr
    address: 0x1
    modbus_id: clivet_modbus
    setup_priority: -10
    update_interval: 10s

sensor:  
  - platform: dallas
    address: 0xF73C01F095BBCC28
    name: "Temperatura Boiler"    
    resolution: 12        
    filters:
      - filter_out: nan    
      - median:
          window_size: 5
          send_every: 5
          send_first_at: 1 

  # Register: 2
  - platform: modbus_controller
    modbus_controller_id: clivet
    name: stc_esphome

    register_type: holding
    address: 0x2
    unit_of_measurement: "°C"
    value_type: U_WORD  
    filters:
      - offset: -30
      - multiply: 0.5
      - filter_out: 0    
      - median:
          window_size: 5
          send_every: 5
          send_first_at: 1  

  # Register: 101
  - platform: modbus_controller
    modbus_controller_id: clivet
    name: tac_esphome

    register_type: holding
    address: 0x65
    unit_of_measurement: "°C"
    value_type: U_WORD  
    filters:
      - offset: -30
      - multiply: 0.5
      - filter_out: 0    
      - median:
          window_size: 5
          send_every: 5
          send_first_at: 1      
```
